---
title: "Welcome to the Quarto Workshop!"
subtitle: A self-paced tutorial on scientific and technical publishing with Quarto
description: The LMU Open Science Center's self-paced Quarto workshop, covering the absolute basics of the scientific and technical publishing system Quarto while using R in RStudio.
---

Welcome to the **Quarto workshop**, initially designed for [LMU OSC Summer School 2023](https://lmu-osc.github.io/OSC-Open-Research-Summer-School-2023/) and [LMU & MPG Open Science Summer School 2024](https://osip.mpdl.mpg.de/lmu-mpg-open-science-summer-school-2024/).

## Tutorial Overview

This **self-paced tutorial** is intended to take about **2 hours** to complete (when skipping the advanced exercises) and is aimed at **early-career researchers**. It covers the absolute basics of the scientific and technical publishing system [Quarto](https://quarto.org/) while using [R in RStudio](https://quarto.org/docs/tools/rstudio.html).

The tutorial is split into the following sections:

1. [**Quarto Tutorials**](quarto-tutorials.qmd) from the official Quarto project
2. [**Tips and Comments**](comments.qmd) from our own experiences of using Quarto
3. [**Advanced Exercises**](quarto-exercises.qmd) that are more challenging than the beginner Quarto tutorials
4. [**Links**](links.qmd) to further resources

::: {.callout-warning title="Recommended Software"}
This tutorial assumes you have the following software installed:

-   [R](https://cran.r-project.org/) and [RStudio](https://posit.co/download/rstudio-desktop/)
-   [Quarto](https://quarto.org/docs/get-started/)
-   A [GitHub](https://github.com/) account (needed for the advanced exercises)

:::

## What is Quarto?

The official [Quarto](https://quarto.org/) website reads:

::: {.callout-tip appearance="minimal" icon=false}
## Quote:

An open-source scientific and technical publishing system

- Author using Jupyter notebooks or with plain text markdown in your favorite editor.
- Create dynamic content with Python, R, Julia, and Observable.
- Publish reproducible, production quality articles, presentations, websites, blogs, and books in HTML, PDF, MS Word, ePub, and more.
- Share knowledge and insights organization-wide by publishing to Posit Connect, Confluence, or other publishing systems.
- Write using Pandoc markdown, including equations, citations, crossrefs, figure panels, callouts, advanced layout, and more.

Analyze. Share. Reproduce. You have a story to tell with data—tell it with Quarto.
:::

These features make Quarto an extremely useful tool for researchers to:

- write reproducible research reports, presentations or scientific articles
- create personal of project websites
- publish tutorials, textbooks, or other educational resources online
- and much more...

If you have not seen many examples yourself, go to the official [Quarto Gallery](https://quarto.org/docs/gallery/), the [Quarto Blog](https://quarto.org/docs/blog/), or have a look at the following presentation for a few examples, where we have used Quarto in our own work:

```{=html}
<iframe class="slide-deck" width="100%" height="500" src="presentation.html"></iframe>
```

::: {.callout-note collapse="true"}
## Live coding example
If you have attended the in-person workshop, you can download the result of the live coding example here:  
{{< downloadthis downloadable/_live-coding-example.zip dname="live-coding-example" label="Download .zip file">}}
:::

## Learn how to use Quarto yourself

When you have finished reading this short introduction and want to learn how to use Quarto for your own projects, go to the [Quarto Tutorials](quarto-tutorials.qmd) page next. :computer: :scream_cat:

:::: {.columns}

::: {.column width="47.5%"}

::: {.callout-tip title="Support the LMU Open Science Center!"}

**Like this tutorial? Be sure to give [the repository]({{< meta repo-url >}}) a star and [follow us on GitHub](https://github.com/lmu-osc)!**
:::

:::

::: {.column width="5%"}
:::

::: {.column width="47.5%"}

::: {.callout-tip title="Questions about this tutorial?"}
**If you have questions for the author of this tutorial, please take a look at the [About](about.qmd) page.**
:::

:::

::::
